apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jdk
    image: maven:3.6.3-jdk-11
    resources:
      limits:
        memory: 8Gi
      requests:
        memory: 8Gi
    command:
      - sleep
    args:
      - infinity
