#!/usr/bin/env bash -eu

DIR=$(dirname "$0")

# Init
$DIR/build || echo "Initial build failed";

#echo "Transpiling TypeScript..."
./node_modules/.bin/tsc --watch --preserveWatchOutput &

#echo "Transpiling SCSS files..."
./node_modules/.bin/node-sass-chokidar src --output ./public --watch --usePolling &

#echo "Webpacking everything..."
./node_modules/.bin/webpack -c webpack.config.js --hide-modules --colors --watch --mode development &


# Keeps the script running
while :; do
  sleep 5
done

