#!/usr/bin/env bash -eu

DIR=$(dirname "$0")

# Init
$DIR/build || echo "Initial build failed";

./node_modules/.bin/webpack -c webpack.config.js --hide-modules --colors --watch --mode development &


# Keeps the script running
while :; do
  sleep 5
done

